# Generated by Django 5.0.3 on 2025-08-09 09:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        default="default_files/default_file.png",
                        upload_to="account_files/images/",
                    ),
                ),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cart_id", models.CharField(max_length=100)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(default="")),
                ("category", models.CharField(default="", max_length=100)),
                ("price", models.CharField(max_length=100)),
                (
                    "image1",
                    models.FileField(
                        blank=True,
                        default="default_files/default_file.png",
                        upload_to="account_files/images/",
                    ),
                ),
                (
                    "image2",
                    models.FileField(
                        blank=True,
                        default="default_files/default_file.png",
                        upload_to="account_files/images/",
                    ),
                ),
                (
                    "image3",
                    models.FileField(
                        blank=True,
                        default="default_files/default_file.png",
                        upload_to="account_files/images/",
                    ),
                ),
                (
                    "image4",
                    models.FileField(
                        blank=True,
                        default="default_files/default_file.png",
                        upload_to="account_files/images/",
                    ),
                ),
                (
                    "image5",
                    models.FileField(
                        blank=True,
                        default="default_files/default_file.png",
                        upload_to="account_files/images/",
                    ),
                ),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("review", models.TextField(default="")),
                ("rating", models.IntegerField(default=0)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_type", models.CharField(max_length=100)),
                ("auth_code", models.CharField(default="null", max_length=20)),
                ("name", models.CharField(default="", max_length=50)),
                ("phone", models.CharField(default="", max_length=50)),
                ("email", models.CharField(default="", max_length=50)),
                ("address", models.TextField(default="")),
                ("delivery_state", models.CharField(default="nowhere", max_length=50)),
                ("streetAddress", models.CharField(default="", max_length=100)),
                ("suite", models.CharField(default="", max_length=100)),
                ("cityAddress", models.CharField(default="", max_length=100)),
                ("order_note", models.CharField(default="", max_length=100)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.cart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "app_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.appuser"
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.cart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppUserOrderConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "app_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.appuser"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.order"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appuser",
            name="orders",
            field=models.ManyToManyField(
                through="main.AppUserOrderConnector", to="main.order"
            ),
        ),
        migrations.CreateModel(
            name="CartProductConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.cart"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                through="main.CartProductConnector", to="main.product"
            ),
        ),
        migrations.CreateModel(
            name="ProductImageConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.image"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductReviewConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.product"
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.review"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="reviews",
            field=models.ManyToManyField(
                through="main.ProductReviewConnector", to="main.review"
            ),
        ),
    ]
