# Generated by Django 4.2.23 on 2025-09-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_sheet',
            field=models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/'),
        ),
    ]
