# Generated by Django 4.2.23 on 2025-09-18 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_data_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighVoltageBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('category', models.CharField(default='', max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image1', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('image2', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('image3', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('image4', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('image5', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('data_sheet', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HighVoltageInverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('category', models.CharField(default='', max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image1', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('image2', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('image3', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('image4', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('image5', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('data_sheet', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LowVoltageBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('category', models.CharField(default='', max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image1', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('image2', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('image3', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('image4', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('image5', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('data_sheet', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LowVoltageInverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('category', models.CharField(default='', max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image1', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('image2', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('image3', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('image4', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('image5', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('data_sheet', models.FileField(blank=True, default='default_files/default_file.png', upload_to='account_files/images/')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
