# Generated by Django 4.2.23 on 2025-11-27 18:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_accessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartLowVoltageInverterConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('LowVoltageInverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lowvoltageinverter')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartLowVoltageBatteryConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('LowVoltageBattery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lowvoltagebattery')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartHighVoltageInverterConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('HighVoltageInverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.highvoltageinverter')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartHighVoltageBatteryConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('HighVoltageBattery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.highvoltagebattery')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartGridTieInverterConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('GridTieInverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gridtieinverter')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartChargersConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Chargers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chargers')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartAccessoriesConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Accessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.accessories')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='Accessories',
            field=models.ManyToManyField(through='main.CartAccessoriesConnector', to='main.accessories'),
        ),
        migrations.AddField(
            model_name='cart',
            name='Chargers',
            field=models.ManyToManyField(through='main.CartChargersConnector', to='main.chargers'),
        ),
        migrations.AddField(
            model_name='cart',
            name='GridTieInverter',
            field=models.ManyToManyField(through='main.CartGridTieInverterConnector', to='main.gridtieinverter'),
        ),
        migrations.AddField(
            model_name='cart',
            name='HighVoltageBattery',
            field=models.ManyToManyField(through='main.CartHighVoltageBatteryConnector', to='main.highvoltagebattery'),
        ),
        migrations.AddField(
            model_name='cart',
            name='HighVoltageInverter',
            field=models.ManyToManyField(through='main.CartHighVoltageInverterConnector', to='main.highvoltageinverter'),
        ),
        migrations.AddField(
            model_name='cart',
            name='LowVoltageBattery',
            field=models.ManyToManyField(through='main.CartLowVoltageBatteryConnector', to='main.lowvoltagebattery'),
        ),
        migrations.AddField(
            model_name='cart',
            name='LowVoltageInverter',
            field=models.ManyToManyField(through='main.CartLowVoltageInverterConnector', to='main.lowvoltageinverter'),
        ),
    ]
